name: "Antora Site"
description: "Generate the Antora site"
branding:
  icon: book-open
  color: yellow
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: false
  antora_generator:
    description: 'Select generator to be used, currently supports the default "@antora/site-generator-default" or a custom generator path'
    required: false
    default: '@antora/site-generator-default'
  antora_custom_generator_dependencies:
    description: 'Enable installing Antora dependencies when using a custom generator'
    required: false
    default: 'false'
  antora_additional_arguments:
    description: 'Pass customized arguments when running Antora'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.antora_playbook}}
    - ${{ inputs.site_sources_path }}
    - ${{ inputs.antora_generator }}
    - ${{ inputs.antora_custom_generator_dependencies }}
    - ${{ inputs.antora_additional_arguments }}
